// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_02Feature : object, Xunit.IClassFixture<NIP_02Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "02.feature"
#line hidden
        
        public NIP_02Feature(NIP_02Feature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-02", "\tFollow list events (kind 3) contain public keys of users the author is following" +
                    ".\r\n\tFollow list is a replaceable event (only the latest version per author is ke" +
                    "pt).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table38.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 7
 testRunner.And("Alice is connected to relay", ((string)(null)), table38, "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table39.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 10
 testRunner.And("Bob is connected to relay", ((string)(null)), table39, "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table40.AddRow(new string[] {
                        "fe8d7a5726ea97ce6140f9fb06b1fe7d3259bcbf8de42c2a5d2ec9f8f0e2f614",
                        "f77f81a6a223eb15f81fee569161a4f729401a9cbc31bb69fef6a949b9d3c23a"});
#line 13
 testRunner.And("Charlie is connected to relay", ((string)(null)), table40, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Publish valid follow list with multiple p tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Publish valid follow list with multiple p tags")]
        public void PublishValidFollowListWithMultiplePTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Publish valid follow list with multiple p tags", "\tAlice publishes a follow list with multiple public keys and can query it back.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table41.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\"],[\"p\",\"f" +
                                "e8d7a5726ea97ce6140f9fb06b1fe7d3259bcbf8de42c2a5d2ec9f8f0e2f614\"]]",
                            "1722337838"});
#line 19
 testRunner.When("Alice publishes an event", ((string)(null)), table41, "When ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table42.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "3"});
#line 22
 testRunner.And("Bob sends a subscription request abcd", ((string)(null)), table42, "And ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table43.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 25
 testRunner.Then("Alice receives a message", ((string)(null)), table43, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table44.AddRow(new string[] {
                            "EVENT",
                            "abcd",
                            "*"});
                table44.AddRow(new string[] {
                            "EOSE",
                            "abcd",
                            ""});
#line 28
 testRunner.And("Bob receives messages", ((string)(null)), table44, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Replace existing follow list with newer timestamp")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Replace existing follow list with newer timestamp")]
        public void ReplaceExistingFollowListWithNewerTimestamp()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Replace existing follow list with newer timestamp", "\tFollow list is a replaceable event, so only the latest version should be stored." +
                    "", tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table45.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\"]]",
                            "1722337838"});
                table45.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"fe8d7a5726ea97ce6140f9fb06b1fe7d3259bcbf8de42c2a5d2ec9f8f0e2f614\"]]",
                            "1722337848"});
#line 35
 testRunner.When("Alice publishes events", ((string)(null)), table45, "When ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table46.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "3"});
#line 39
 testRunner.And("Bob sends a subscription request abcd", ((string)(null)), table46, "And ");
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table47.AddRow(new string[] {
                            "EVENT",
                            "abcd",
                            "*"});
                table47.AddRow(new string[] {
                            "EOSE",
                            "abcd",
                            ""});
#line 42
 testRunner.Then("Bob receives messages", ((string)(null)), table47, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Follow list with relay hints and petnames")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Follow list with relay hints and petnames")]
        public void FollowListWithRelayHintsAndPetnames()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow list with relay hints and petnames", "\tFollow list p tags can include optional relay URL and petname.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table48.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\",\"wss://r" +
                                "elay.example.com\",\"bob\"],[\"p\",\"fe8d7a5726ea97ce6140f9fb06b1fe7d3259bcbf8de42c2a5" +
                                "d2ec9f8f0e2f614\",\"wss://nostr.example.com\",\"charlie\"]]",
                            "1722337838"});
#line 49
 testRunner.When("Alice publishes an event", ((string)(null)), table48, "When ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table49.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 52
 testRunner.Then("Alice receives a message", ((string)(null)), table49, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty follow list with no p tags is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Empty follow list with no p tags is valid")]
        public void EmptyFollowListWithNoPTagsIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Empty follow list with no p tags is valid", "\tA follow list with no contacts is valid.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table50.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "",
                            "1722337838"});
#line 58
 testRunner.When("Alice publishes an event", ((string)(null)), table50, "When ");
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table51.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 61
 testRunner.Then("Alice receives a message", ((string)(null)), table51, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Follow list with content is valid for backwards compatibility")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Follow list with content is valid for backwards compatibility")]
        public void FollowListWithContentIsValidForBackwardsCompatibility()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow list with content is valid for backwards compatibility", "\tNIP-02 says content is not used but some clients store relay info there.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table52.AddRow(new string[] {
                            "*",
                            "{\"wss://relay.example.com\":{\"write\":true}}",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\"]]",
                            "1722337838"});
#line 67
 testRunner.When("Alice publishes an event", ((string)(null)), table52, "When ");
#line hidden
                TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table53.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 70
 testRunner.Then("Alice receives a message", ((string)(null)), table53, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject follow list with invalid pubkey format - wrong length")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Reject follow list with invalid pubkey format - wrong length")]
        public void RejectFollowListWithInvalidPubkeyFormat_WrongLength()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject follow list with invalid pubkey format - wrong length", "\tPublic keys must be 64-character hex strings.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table54.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"abc123\"]]",
                            "1722337838"});
#line 76
 testRunner.When("Alice publishes an event", ((string)(null)), table54, "When ");
#line hidden
                TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table55.AddRow(new string[] {
                            "OK",
                            "*",
                            "false",
                            "invalid: follow list contains invalid pubkey format"});
#line 79
 testRunner.Then("Alice receives a message", ((string)(null)), table55, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject follow list with invalid pubkey format - non-hex characters")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Reject follow list with invalid pubkey format - non-hex characters")]
        public void RejectFollowListWithInvalidPubkeyFormat_Non_HexCharacters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject follow list with invalid pubkey format - non-hex characters", "\tPublic keys must only contain hexadecimal characters.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table56.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\"]]",
                            "1722337838"});
#line 85
 testRunner.When("Alice publishes an event", ((string)(null)), table56, "When ");
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table57.AddRow(new string[] {
                            "OK",
                            "*",
                            "false",
                            "invalid: follow list contains invalid pubkey format"});
#line 88
 testRunner.Then("Alice receives a message", ((string)(null)), table57, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject follow list with invalid relay URL")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Reject follow list with invalid relay URL")]
        public void RejectFollowListWithInvalidRelayURL()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject follow list with invalid relay URL", "\tRelay URLs must be valid absolute URIs.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table58.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\",\"not-a-v" +
                                "alid-url\"]]",
                            "1722337838"});
#line 94
 testRunner.When("Alice publishes an event", ((string)(null)), table58, "When ");
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table59.AddRow(new string[] {
                            "OK",
                            "*",
                            "false",
                            "invalid: follow list contains invalid relay URL"});
#line 97
 testRunner.Then("Alice receives a message", ((string)(null)), table59, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject follow list with non-p tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Reject follow list with non-p tags")]
        public void RejectFollowListWithNon_PTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject follow list with non-p tags", "\tFollow list should only contain p tags.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table60.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\"],[\"e\",\"a" +
                                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"]]",
                            "1722337838"});
#line 103
 testRunner.When("Alice publishes an event", ((string)(null)), table60, "When ");
#line hidden
                TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table61.AddRow(new string[] {
                            "OK",
                            "*",
                            "false",
                            "invalid: follow list must only contain \'p\' tags"});
#line 106
 testRunner.Then("Alice receives a message", ((string)(null)), table61, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query follow list by author pubkey")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-02")]
        [Xunit.TraitAttribute("Description", "Query follow list by author pubkey")]
        public void QueryFollowListByAuthorPubkey()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query follow list by author pubkey", "\tBob and Charlie both have follow lists, Alice can query them by author.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table62.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75\"]]",
                            "1722337838"});
#line 112
 testRunner.When("Bob publishes an event", ((string)(null)), table62, "When ");
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table63.AddRow(new string[] {
                            "*",
                            "*",
                            "3",
                            "[[\"p\",\"5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627\"]]",
                            "1722337838"});
#line 115
 testRunner.And("Charlie publishes an event", ((string)(null)), table63, "And ");
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table64.AddRow(new string[] {
                            "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                            "3"});
#line 118
 testRunner.And("Alice sends a subscription request follow_sub", ((string)(null)), table64, "And ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table65.AddRow(new string[] {
                            "EVENT",
                            "follow_sub",
                            "*"});
                table65.AddRow(new string[] {
                            "EOSE",
                            "follow_sub",
                            ""});
#line 121
 testRunner.Then("Alice receives messages", ((string)(null)), table65, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_02Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_02Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
