// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_05Feature : object, Xunit.IClassFixture<NIP_05Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "05.feature"
#line hidden
        
        public NIP_05Feature(NIP_05Feature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-05", "\tDNS-based identity verification for user metadata (kind 0) events.\r\n\tNIP-05 iden" +
                    "tifiers follow the format: local-part@domain\r\n\tVerification is done asynchronous" +
                    "ly and never rejects events.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table77.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 8
 testRunner.And("Alice is connected to relay", ((string)(null)), table77, "And ");
#line hidden
            TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table78.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 11
 testRunner.And("Bob is connected to relay", ((string)(null)), table78, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accept metadata event with NIP-05 identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Accept metadata event with NIP-05 identifier")]
        public void AcceptMetadataEventWithNIP_05Identifier()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accept metadata event with NIP-05 identifier", "\tNIP-05 validation runs asynchronously and never rejects events.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table79.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice\",\"nip05\":\"alice@example.com\"}",
                            "0",
                            "",
                            "1722337838"});
#line 17
 testRunner.When("Alice publishes an event", ((string)(null)), table79, "When ");
#line hidden
                TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table80.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 20
 testRunner.Then("Alice receives a message", ((string)(null)), table80, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accept metadata event without NIP-05 identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Accept metadata event without NIP-05 identifier")]
        public void AcceptMetadataEventWithoutNIP_05Identifier()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accept metadata event without NIP-05 identifier", "\tEvents without NIP-05 field are valid.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table81.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice\",\"about\":\"test\"}",
                            "0",
                            "",
                            "1722337838"});
#line 26
 testRunner.When("Alice publishes an event", ((string)(null)), table81, "When ");
#line hidden
                TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table82.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 29
 testRunner.Then("Alice receives a message", ((string)(null)), table82, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accept metadata event with empty NIP-05 identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Accept metadata event with empty NIP-05 identifier")]
        public void AcceptMetadataEventWithEmptyNIP_05Identifier()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accept metadata event with empty NIP-05 identifier", "\tEmpty NIP-05 field should be accepted.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table83.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice\",\"nip05\":\"\"}",
                            "0",
                            "",
                            "1722337838"});
#line 35
 testRunner.When("Alice publishes an event", ((string)(null)), table83, "When ");
#line hidden
                TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table84.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 38
 testRunner.Then("Alice receives a message", ((string)(null)), table84, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accept metadata event with root identifier")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Accept metadata event with root identifier")]
        public void AcceptMetadataEventWithRootIdentifier()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accept metadata event with root identifier", "\tRoot identifier uses underscore: _@domain.com", tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table85 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table85.AddRow(new string[] {
                            "*",
                            "{\"name\":\"example.com\",\"nip05\":\"_@example.com\"}",
                            "0",
                            "",
                            "1722337838"});
#line 44
 testRunner.When("Alice publishes an event", ((string)(null)), table85, "When ");
#line hidden
                TechTalk.SpecFlow.Table table86 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table86.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 47
 testRunner.Then("Alice receives a message", ((string)(null)), table86, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accept metadata event with invalid NIP-05 format")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Accept metadata event with invalid NIP-05 format")]
        public void AcceptMetadataEventWithInvalidNIP_05Format()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accept metadata event with invalid NIP-05 format", "\tInvalid NIP-05 format is still accepted, verification just fails silently.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table87 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table87.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice\",\"nip05\":\"invalid-no-at-sign\"}",
                            "0",
                            "",
                            "1722337838"});
#line 53
 testRunner.When("Alice publishes an event", ((string)(null)), table87, "When ");
#line hidden
                TechTalk.SpecFlow.Table table88 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table88.AddRow(new string[] {
                            "OK",
                            "*",
                            "true"});
#line 56
 testRunner.Then("Alice receives a message", ((string)(null)), table88, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query metadata by author")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Query metadata by author")]
        public void QueryMetadataByAuthor()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query metadata by author", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table89 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table89.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice\",\"nip05\":\"alice@example.com\",\"picture\":\"https://example.com/pic.jp" +
                                "g\"}",
                            "0",
                            "",
                            "1722337838"});
#line 61
 testRunner.When("Alice publishes an event", ((string)(null)), table89, "When ");
#line hidden
                TechTalk.SpecFlow.Table table90 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table90.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "0"});
#line 64
 testRunner.And("Bob sends a subscription request metadata_sub", ((string)(null)), table90, "And ");
#line hidden
                TechTalk.SpecFlow.Table table91 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table91.AddRow(new string[] {
                            "EVENT",
                            "metadata_sub",
                            "*"});
                table91.AddRow(new string[] {
                            "EOSE",
                            "metadata_sub",
                            ""});
#line 67
 testRunner.Then("Bob receives messages", ((string)(null)), table91, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Metadata event is replaceable")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-05")]
        [Xunit.TraitAttribute("Description", "Metadata event is replaceable")]
        public void MetadataEventIsReplaceable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Metadata event is replaceable", "\tOnly the latest metadata event should be stored per author.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table92 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table92.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice_old\"}",
                            "0",
                            "",
                            "1722337838"});
                table92.AddRow(new string[] {
                            "*",
                            "{\"name\":\"alice_new\"}",
                            "0",
                            "",
                            "1722337848"});
#line 74
 testRunner.When("Alice publishes events", ((string)(null)), table92, "When ");
#line hidden
                TechTalk.SpecFlow.Table table93 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table93.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "0"});
#line 78
 testRunner.And("Bob sends a subscription request metadata_sub", ((string)(null)), table93, "And ");
#line hidden
                TechTalk.SpecFlow.Table table94 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table94.AddRow(new string[] {
                            "EVENT",
                            "metadata_sub",
                            "*"});
                table94.AddRow(new string[] {
                            "EOSE",
                            "metadata_sub",
                            ""});
#line 81
 testRunner.Then("Bob receives messages", ((string)(null)), table94, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_05Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_05Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
