// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_51Feature : object, Xunit.IClassFixture<NIP_51Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "51.feature"
#line hidden
        
        public NIP_51Feature(NIP_51Feature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-51", "\tStandard lists (kinds 10000-10999) are replaceable per author.\r\n\tSets (kinds 300" +
                    "00-30999) are addressable and require a \"d\" tag identifier.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table186 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table186.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 7
 testRunner.And("Alice is connected to relay", ((string)(null)), table186, "And ");
#line hidden
            TechTalk.SpecFlow.Table table187 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table187.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 10
 testRunner.And("Bob is connected to relay", ((string)(null)), table187, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create public mute list with p tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create public mute list with p tags")]
        public void CreatePublicMuteListWithPTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create public mute list with p tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table188 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table188.AddRow(new string[] {
                            "1111111111111111111111111111111111111111111111111111111111111111",
                            "*",
                            "10000",
                            "[[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc1da3a9\"],[\"p\",\"a" +
                                "55c15f5e41d5aebd236eca5e0142789c5385703f1a7485aa4b38d94fd18dcc4\"]]",
                            "1722337838"});
#line 16
 testRunner.When("Alice publishes an event", ((string)(null)), table188, "When ");
#line hidden
                TechTalk.SpecFlow.Table table189 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table189.AddRow(new string[] {
                            "OK",
                            "1111111111111111111111111111111111111111111111111111111111111111",
                            "true"});
#line 19
 testRunner.Then("Alice receives a message", ((string)(null)), table189, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create mute list with hashtag and word tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create mute list with hashtag and word tags")]
        public void CreateMuteListWithHashtagAndWordTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create mute list with hashtag and word tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table190 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table190.AddRow(new string[] {
                            "2222222222222222222222222222222222222222222222222222222222222222",
                            "*",
                            "10000",
                            "[[\"t\",\"spam\"],[\"word\",\"scam\"],[\"word\",\"rugpull\"]]",
                            "1722337838"});
#line 24
 testRunner.When("Alice publishes an event", ((string)(null)), table190, "When ");
#line hidden
                TechTalk.SpecFlow.Table table191 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table191.AddRow(new string[] {
                            "OK",
                            "2222222222222222222222222222222222222222222222222222222222222222",
                            "true"});
#line 27
 testRunner.Then("Alice receives a message", ((string)(null)), table191, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query mute list by author")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Query mute list by author")]
        public void QueryMuteListByAuthor()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query mute list by author", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table192 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table192.AddRow(new string[] {
                            "3333333333333333333333333333333333333333333333333333333333333333",
                            "*",
                            "10000",
                            "[[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc1da3a9\"]]",
                            "1722337838"});
#line 32
 testRunner.When("Alice publishes an event", ((string)(null)), table192, "When ");
#line hidden
                TechTalk.SpecFlow.Table table193 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table193.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "10000"});
#line 35
 testRunner.And("Bob sends a subscription request mute_sub", ((string)(null)), table193, "And ");
#line hidden
                TechTalk.SpecFlow.Table table194 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table194.AddRow(new string[] {
                            "EVENT",
                            "mute_sub",
                            "3333333333333333333333333333333333333333333333333333333333333333"});
                table194.AddRow(new string[] {
                            "EOSE",
                            "mute_sub",
                            ""});
#line 38
 testRunner.Then("Bob receives messages", ((string)(null)), table194, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create bookmarks with event and article references")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create bookmarks with event and article references")]
        public void CreateBookmarksWithEventAndArticleReferences()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create bookmarks with event and article references", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table195 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table195.AddRow(new string[] {
                            "4444444444444444444444444444444444444444444444444444444444444444",
                            "*",
                            "10003",
                            "[[\"e\",\"d78ba0d5dce22bfff9db0a9e996c9ef27e2c91051de0c4e1da340e0326b4941e\"],[\"a\",\"3" +
                                "0023:26dc95542e18b8b7aec2f14610f55c335abebec76f3db9e58c254661d0593a0c:95ODQzw3\"]" +
                                "]",
                            "1722337838"});
#line 45
 testRunner.When("Alice publishes an event", ((string)(null)), table195, "When ");
#line hidden
                TechTalk.SpecFlow.Table table196 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table196.AddRow(new string[] {
                            "OK",
                            "4444444444444444444444444444444444444444444444444444444444444444",
                            "true"});
#line 48
 testRunner.Then("Alice receives a message", ((string)(null)), table196, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create blocked relays list")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create blocked relays list")]
        public void CreateBlockedRelaysList()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create blocked relays list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table197 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table197.AddRow(new string[] {
                            "5555555555555555555555555555555555555555555555555555555555555555",
                            "*",
                            "10006",
                            "[[\"relay\",\"wss://badrelay1.com\"],[\"relay\",\"wss://badrelay2.com\"]]",
                            "1722337838"});
#line 54
 testRunner.When("Alice publishes an event", ((string)(null)), table197, "When ");
#line hidden
                TechTalk.SpecFlow.Table table198 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table198.AddRow(new string[] {
                            "OK",
                            "5555555555555555555555555555555555555555555555555555555555555555",
                            "true"});
#line 57
 testRunner.Then("Alice receives a message", ((string)(null)), table198, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create interests list")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create interests list")]
        public void CreateInterestsList()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create interests list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table199 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table199.AddRow(new string[] {
                            "6666666666666666666666666666666666666666666666666666666666666666",
                            "*",
                            "10015",
                            "[[\"t\",\"bitcoin\"],[\"t\",\"nostr\"],[\"t\",\"programming\"]]",
                            "1722337838"});
#line 63
 testRunner.When("Alice publishes an event", ((string)(null)), table199, "When ");
#line hidden
                TechTalk.SpecFlow.Table table200 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table200.AddRow(new string[] {
                            "OK",
                            "6666666666666666666666666666666666666666666666666666666666666666",
                            "true"});
#line 66
 testRunner.Then("Alice receives a message", ((string)(null)), table200, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create emoji list with emoji tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create emoji list with emoji tags")]
        public void CreateEmojiListWithEmojiTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create emoji list with emoji tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table201 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table201.AddRow(new string[] {
                            "7777777777777777777777777777777777777777777777777777777777777777",
                            "*",
                            "10030",
                            "[[\"emoji\",\"happy\",\"https://example.com/happy.png\"],[\"emoji\",\"sad\",\"https://exampl" +
                                "e.com/sad.png\"]]",
                            "1722337838"});
#line 72
 testRunner.When("Alice publishes an event", ((string)(null)), table201, "When ");
#line hidden
                TechTalk.SpecFlow.Table table202 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table202.AddRow(new string[] {
                            "OK",
                            "7777777777777777777777777777777777777777777777777777777777777777",
                            "true"});
#line 75
 testRunner.Then("Alice receives a message", ((string)(null)), table202, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create follow set with d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create follow set with d tag")]
        public void CreateFollowSetWithDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create follow set with d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table203 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table203.AddRow(new string[] {
                            "8888888888888888888888888888888888888888888888888888888888888888",
                            "*",
                            "30000",
                            "[[\"d\",\"friends\"],[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc" +
                                "1da3a9\"],[\"p\",\"a55c15f5e41d5aebd236eca5e0142789c5385703f1a7485aa4b38d94fd18dcc4\"" +
                                "]]",
                            "1722337838"});
#line 81
 testRunner.When("Alice publishes an event", ((string)(null)), table203, "When ");
#line hidden
                TechTalk.SpecFlow.Table table204 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table204.AddRow(new string[] {
                            "OK",
                            "8888888888888888888888888888888888888888888888888888888888888888",
                            "true"});
#line 84
 testRunner.Then("Alice receives a message", ((string)(null)), table204, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject follow set without d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Reject follow set without d tag")]
        public void RejectFollowSetWithoutDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject follow set without d tag", "\tSets require a d tag identifier.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table205 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table205.AddRow(new string[] {
                            "9999999999999999999999999999999999999999999999999999999999999999",
                            "*",
                            "30000",
                            "[[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc1da3a9\"]]",
                            "1722337838"});
#line 90
 testRunner.When("Alice publishes an event", ((string)(null)), table205, "When ");
#line hidden
                TechTalk.SpecFlow.Table table206 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table206.AddRow(new string[] {
                            "OK",
                            "9999999999999999999999999999999999999999999999999999999999999999",
                            "false",
                            "*"});
#line 93
 testRunner.Then("Alice receives a message", ((string)(null)), table206, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create relay set with d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create relay set with d tag")]
        public void CreateRelaySetWithDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create relay set with d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table207 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table207.AddRow(new string[] {
                            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "*",
                            "30002",
                            "[[\"d\",\"my-relays\"],[\"relay\",\"wss://relay1.example.com\"],[\"relay\",\"wss://relay2.ex" +
                                "ample.com\"]]",
                            "1722337838"});
#line 99
 testRunner.When("Alice publishes an event", ((string)(null)), table207, "When ");
#line hidden
                TechTalk.SpecFlow.Table table208 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table208.AddRow(new string[] {
                            "OK",
                            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "true"});
#line 102
 testRunner.Then("Alice receives a message", ((string)(null)), table208, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create bookmark set with d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create bookmark set with d tag")]
        public void CreateBookmarkSetWithDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create bookmark set with d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table209 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table209.AddRow(new string[] {
                            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                            "*",
                            "30003",
                            "[[\"d\",\"programming\"],[\"e\",\"d78ba0d5dce22bfff9db0a9e996c9ef27e2c91051de0c4e1da340e" +
                                "0326b4941e\"],[\"a\",\"30023:26dc95542e18b8b7aec2f14610f55c335abebec76f3db9e58c25466" +
                                "1d0593a0c:95ODQzw3\"]]",
                            "1722337838"});
#line 108
 testRunner.When("Alice publishes an event", ((string)(null)), table209, "When ");
#line hidden
                TechTalk.SpecFlow.Table table210 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table210.AddRow(new string[] {
                            "OK",
                            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                            "true"});
#line 111
 testRunner.Then("Alice receives a message", ((string)(null)), table210, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create kind mute set with d tag as kind number")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create kind mute set with d tag as kind number")]
        public void CreateKindMuteSetWithDTagAsKindNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create kind mute set with d tag as kind number", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table211 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table211.AddRow(new string[] {
                            "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
                            "*",
                            "30007",
                            "[[\"d\",\"1\"],[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc1da3a9" +
                                "\"],[\"p\",\"a55c15f5e41d5aebd236eca5e0142789c5385703f1a7485aa4b38d94fd18dcc4\"]]",
                            "1722337838"});
#line 117
 testRunner.When("Alice publishes an event", ((string)(null)), table211, "When ");
#line hidden
                TechTalk.SpecFlow.Table table212 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table212.AddRow(new string[] {
                            "OK",
                            "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
                            "true"});
#line 120
 testRunner.Then("Alice receives a message", ((string)(null)), table212, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create interest set with d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create interest set with d tag")]
        public void CreateInterestSetWithDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create interest set with d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 125
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table213 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table213.AddRow(new string[] {
                            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
                            "*",
                            "30015",
                            "[[\"d\",\"tech\"],[\"t\",\"bitcoin\"],[\"t\",\"programming\"]]",
                            "1722337838"});
#line 126
 testRunner.When("Alice publishes an event", ((string)(null)), table213, "When ");
#line hidden
                TechTalk.SpecFlow.Table table214 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table214.AddRow(new string[] {
                            "OK",
                            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
                            "true"});
#line 129
 testRunner.Then("Alice receives a message", ((string)(null)), table214, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create emoji set with d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Create emoji set with d tag")]
        public void CreateEmojiSetWithDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create emoji set with d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 134
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table215 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table215.AddRow(new string[] {
                            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
                            "*",
                            "30030",
                            "[[\"d\",\"reactions\"],[\"emoji\",\"thumbsup\",\"https://example.com/thumbsup.png\"],[\"emoj" +
                                "i\",\"fire\",\"https://example.com/fire.png\"]]",
                            "1722337838"});
#line 135
 testRunner.When("Alice publishes an event", ((string)(null)), table215, "When ");
#line hidden
                TechTalk.SpecFlow.Table table216 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table216.AddRow(new string[] {
                            "OK",
                            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
                            "true"});
#line 138
 testRunner.Then("Alice receives a message", ((string)(null)), table216, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update addressable list replaces previous with same d tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-51")]
        [Xunit.TraitAttribute("Description", "Update addressable list replaces previous with same d tag")]
        public void UpdateAddressableListReplacesPreviousWithSameDTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update addressable list replaces previous with same d tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table217 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table217.AddRow(new string[] {
                            "*",
                            "*",
                            "30000",
                            "[[\"d\",\"friends\"],[\"p\",\"07caba282f76441955b695551c3c5c742e5b9202a3784780f8086fdcdc" +
                                "1da3a9\"]]",
                            "1722337838"});
                table217.AddRow(new string[] {
                            "*",
                            "*",
                            "30000",
                            "[[\"d\",\"friends\"],[\"p\",\"a55c15f5e41d5aebd236eca5e0142789c5385703f1a7485aa4b38d94fd" +
                                "18dcc4\"]]",
                            "1722337848"});
#line 144
 testRunner.When("Alice publishes events", ((string)(null)), table217, "When ");
#line hidden
                TechTalk.SpecFlow.Table table218 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table218.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "30000"});
#line 148
 testRunner.And("Bob sends a subscription request set_sub", ((string)(null)), table218, "And ");
#line hidden
                TechTalk.SpecFlow.Table table219 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table219.AddRow(new string[] {
                            "EVENT",
                            "set_sub",
                            "*"});
                table219.AddRow(new string[] {
                            "EOSE",
                            "set_sub",
                            ""});
#line 151
 testRunner.Then("Bob receives messages", ((string)(null)), table219, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_51Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_51Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
