// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_57Feature : object, Xunit.IClassFixture<NIP_57Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "57.feature"
#line hidden
        
        public NIP_57Feature(NIP_57Feature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-57", "\tLightning Zaps enable Bitcoin payments on nostr.\r\n\tZap Request (kind 9734) is se" +
                    "nt to initiate a zap.\r\n\tZap Receipt (kind 9735) is published after payment confi" +
                    "rmation.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table220 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table220.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 8
 testRunner.And("Alice is connected to relay", ((string)(null)), table220, "And ");
#line hidden
            TechTalk.SpecFlow.Table table221 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table221.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 11
 testRunner.And("Bob is connected to relay", ((string)(null)), table221, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create valid zap request with required tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Create valid zap request with required tags")]
        public void CreateValidZapRequestWithRequiredTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create valid zap request with required tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table222 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table222.AddRow(new string[] {
                            "1111111111111111111111111111111111111111111111111111111111111111",
                            "*",
                            "9734",
                            "[[\"p\",\"04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9\"],[\"relay" +
                                "s\",\"wss://relay1.example.com\",\"wss://relay2.example.com\"]]",
                            "1722337838"});
#line 17
 testRunner.When("Alice publishes an event", ((string)(null)), table222, "When ");
#line hidden
                TechTalk.SpecFlow.Table table223 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table223.AddRow(new string[] {
                            "OK",
                            "1111111111111111111111111111111111111111111111111111111111111111",
                            "true"});
#line 20
 testRunner.Then("Alice receives a message", ((string)(null)), table223, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create zap request with amount and lnurl")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Create zap request with amount and lnurl")]
        public void CreateZapRequestWithAmountAndLnurl()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create zap request with amount and lnurl", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table224 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table224.AddRow(new string[] {
                            "2222222222222222222222222222222222222222222222222222222222222222",
                            "*",
                            "9734",
                            "[[\"p\",\"04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9\"],[\"relay" +
                                "s\",\"wss://relay1.example.com\"],[\"amount\",\"21000\"],[\"lnurl\",\"lnurl1dp68gurn8ghj7u" +
                                "m5v93kketj9ehx2amn9uh8wetvdskkkmn0wahz7mrww4excup0dajx2mrv92x9xp\"]]",
                            "1722337838"});
#line 25
 testRunner.When("Alice publishes an event", ((string)(null)), table224, "When ");
#line hidden
                TechTalk.SpecFlow.Table table225 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table225.AddRow(new string[] {
                            "OK",
                            "2222222222222222222222222222222222222222222222222222222222222222",
                            "true"});
#line 28
 testRunner.Then("Alice receives a message", ((string)(null)), table225, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create zap request with e tag for specific event")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Create zap request with e tag for specific event")]
        public void CreateZapRequestWithETagForSpecificEvent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create zap request with e tag for specific event", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table226 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table226.AddRow(new string[] {
                            "3333333333333333333333333333333333333333333333333333333333333333",
                            "*",
                            "9734",
                            "[[\"p\",\"04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9\"],[\"relay" +
                                "s\",\"wss://relay1.example.com\"],[\"e\",\"3624762a1274dd9636e0c552b53086d70bc88c165bc" +
                                "4dc0f9e836a1eaf86c3b8\"]]",
                            "1722337838"});
#line 33
 testRunner.When("Alice publishes an event", ((string)(null)), table226, "When ");
#line hidden
                TechTalk.SpecFlow.Table table227 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table227.AddRow(new string[] {
                            "OK",
                            "3333333333333333333333333333333333333333333333333333333333333333",
                            "true"});
#line 36
 testRunner.Then("Alice receives a message", ((string)(null)), table227, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject zap request without p tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Reject zap request without p tag")]
        public void RejectZapRequestWithoutPTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject zap request without p tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table228 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table228.AddRow(new string[] {
                            "4444444444444444444444444444444444444444444444444444444444444444",
                            "*",
                            "9734",
                            "[[\"relays\",\"wss://relay1.example.com\"]]",
                            "1722337838"});
#line 41
 testRunner.When("Alice publishes an event", ((string)(null)), table228, "When ");
#line hidden
                TechTalk.SpecFlow.Table table229 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table229.AddRow(new string[] {
                            "OK",
                            "4444444444444444444444444444444444444444444444444444444444444444",
                            "false",
                            "*"});
#line 44
 testRunner.Then("Alice receives a message", ((string)(null)), table229, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject zap request without relays tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Reject zap request without relays tag")]
        public void RejectZapRequestWithoutRelaysTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject zap request without relays tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table230 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table230.AddRow(new string[] {
                            "5555555555555555555555555555555555555555555555555555555555555555",
                            "*",
                            "9734",
                            "[[\"p\",\"04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9\"]]",
                            "1722337838"});
#line 49
 testRunner.When("Alice publishes an event", ((string)(null)), table230, "When ");
#line hidden
                TechTalk.SpecFlow.Table table231 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table231.AddRow(new string[] {
                            "OK",
                            "5555555555555555555555555555555555555555555555555555555555555555",
                            "false",
                            "*"});
#line 52
 testRunner.Then("Alice receives a message", ((string)(null)), table231, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create valid zap receipt with required tags")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Create valid zap receipt with required tags")]
        public void CreateValidZapReceiptWithRequiredTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create valid zap receipt with required tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table232 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table232.AddRow(new string[] {
                            "6666666666666666666666666666666666666666666666666666666666666666",
                            "*",
                            "9735",
                            @"[[""p"",""32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245""],[""bolt11"",""lnbc10u1p3unwfusp5t9r3yymhpfqculx78u027lxspgxcr2n2987mx2j55nnfs95nxnzqpp5jmrh92pfld78spqs78v9euf2385t83uvpwk9ldrlvf6ch7tpascqhp5zvkrmemgth3tufcvflmzjzfvjt023nazlhljz2n9hattj4f8jq8qxqyjw5qcqpjrzjq""],[""description"",""{\""pubkey\"":\""test\"",\""kind\"":9734}""]]",
                            "1722337838"});
#line 58
 testRunner.When("Alice publishes an event", ((string)(null)), table232, "When ");
#line hidden
                TechTalk.SpecFlow.Table table233 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table233.AddRow(new string[] {
                            "OK",
                            "6666666666666666666666666666666666666666666666666666666666666666",
                            "true"});
#line 61
 testRunner.Then("Alice receives a message", ((string)(null)), table233, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create zap receipt with preimage")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Create zap receipt with preimage")]
        public void CreateZapReceiptWithPreimage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create zap receipt with preimage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table234 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table234.AddRow(new string[] {
                            "7777777777777777777777777777777777777777777777777777777777777777",
                            "*",
                            "9735",
                            "[[\"p\",\"32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245\"],[\"bolt1" +
                                "1\",\"lnbc10u1\"],[\"description\",\"{\\\"pubkey\\\":\\\"test\\\",\\\"kind\\\":9734}\"],[\"preimage\"" +
                                ",\"5d006d2cf1e73c7148e7519a4c68adc81642ce0e25a432b2434c99f97344c15f\"]]",
                            "1722337838"});
#line 66
 testRunner.When("Alice publishes an event", ((string)(null)), table234, "When ");
#line hidden
                TechTalk.SpecFlow.Table table235 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success"});
                table235.AddRow(new string[] {
                            "OK",
                            "7777777777777777777777777777777777777777777777777777777777777777",
                            "true"});
#line 69
 testRunner.Then("Alice receives a message", ((string)(null)), table235, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject zap receipt without p tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Reject zap receipt without p tag")]
        public void RejectZapReceiptWithoutPTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject zap receipt without p tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table236 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table236.AddRow(new string[] {
                            "8888888888888888888888888888888888888888888888888888888888888888",
                            "*",
                            "9735",
                            "[[\"bolt11\",\"lnbc10u1\"],[\"description\",\"{\\\"pubkey\\\":\\\"test\\\",\\\"kind\\\":9734}\"]]",
                            "1722337838"});
#line 74
 testRunner.When("Alice publishes an event", ((string)(null)), table236, "When ");
#line hidden
                TechTalk.SpecFlow.Table table237 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table237.AddRow(new string[] {
                            "OK",
                            "8888888888888888888888888888888888888888888888888888888888888888",
                            "false",
                            "*"});
#line 77
 testRunner.Then("Alice receives a message", ((string)(null)), table237, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject zap receipt without bolt11 tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Reject zap receipt without bolt11 tag")]
        public void RejectZapReceiptWithoutBolt11Tag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject zap receipt without bolt11 tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table238 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table238.AddRow(new string[] {
                            "9999999999999999999999999999999999999999999999999999999999999999",
                            "*",
                            "9735",
                            "[[\"p\",\"32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245\"],[\"descr" +
                                "iption\",\"{\\\"pubkey\\\":\\\"test\\\",\\\"kind\\\":9734}\"]]",
                            "1722337838"});
#line 82
 testRunner.When("Alice publishes an event", ((string)(null)), table238, "When ");
#line hidden
                TechTalk.SpecFlow.Table table239 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table239.AddRow(new string[] {
                            "OK",
                            "9999999999999999999999999999999999999999999999999999999999999999",
                            "false",
                            "*"});
#line 85
 testRunner.Then("Alice receives a message", ((string)(null)), table239, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject zap receipt without description tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Reject zap receipt without description tag")]
        public void RejectZapReceiptWithoutDescriptionTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject zap receipt without description tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table240 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table240.AddRow(new string[] {
                            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "*",
                            "9735",
                            "[[\"p\",\"32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245\"],[\"bolt1" +
                                "1\",\"lnbc10u1\"]]",
                            "1722337838"});
#line 90
 testRunner.When("Alice publishes an event", ((string)(null)), table240, "When ");
#line hidden
                TechTalk.SpecFlow.Table table241 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "Success",
                            "Message"});
                table241.AddRow(new string[] {
                            "OK",
                            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "false",
                            "*"});
#line 93
 testRunner.Then("Alice receives a message", ((string)(null)), table241, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query zap requests by kind")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Query zap requests by kind")]
        public void QueryZapRequestsByKind()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query zap requests by kind", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table242 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table242.AddRow(new string[] {
                            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                            "*",
                            "9734",
                            "[[\"p\",\"04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9\"],[\"relay" +
                                "s\",\"wss://relay1.example.com\"]]",
                            "1722337838"});
#line 99
 testRunner.When("Alice publishes an event", ((string)(null)), table242, "When ");
#line hidden
                TechTalk.SpecFlow.Table table243 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table243.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "9734"});
#line 102
 testRunner.And("Bob sends a subscription request zap_sub", ((string)(null)), table243, "And ");
#line hidden
                TechTalk.SpecFlow.Table table244 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table244.AddRow(new string[] {
                            "EVENT",
                            "zap_sub",
                            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"});
                table244.AddRow(new string[] {
                            "EOSE",
                            "zap_sub",
                            ""});
#line 105
 testRunner.Then("Bob receives messages", ((string)(null)), table244, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Query zap receipts by kind")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-57")]
        [Xunit.TraitAttribute("Description", "Query zap receipts by kind")]
        public void QueryZapReceiptsByKind()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Query zap receipts by kind", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table245 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table245.AddRow(new string[] {
                            "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
                            "*",
                            "9735",
                            "[[\"p\",\"32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245\"],[\"bolt1" +
                                "1\",\"lnbc10u1\"],[\"description\",\"{\\\"pubkey\\\":\\\"test\\\",\\\"kind\\\":9734}\"]]",
                            "1722337838"});
#line 111
 testRunner.When("Alice publishes an event", ((string)(null)), table245, "When ");
#line hidden
                TechTalk.SpecFlow.Table table246 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors",
                            "Kinds"});
                table246.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                            "9735"});
#line 114
 testRunner.And("Bob sends a subscription request zap_sub", ((string)(null)), table246, "And ");
#line hidden
                TechTalk.SpecFlow.Table table247 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table247.AddRow(new string[] {
                            "EVENT",
                            "zap_sub",
                            "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"});
                table247.AddRow(new string[] {
                            "EOSE",
                            "zap_sub",
                            ""});
#line 117
 testRunner.Then("Bob receives messages", ((string)(null)), table247, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_57Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_57Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
